name: Upload to CDN and publish image
description: Uploads nextjs static files to CDN and publishes docker image to GAR

inputs:
  app:
    required: true
    description: app name
  team:
    required: true
    description: team name
  env:
    required: true
    description: GAR prefix

outputs:
  image:
    description: The image name and tag in GAR
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: composite
  steps:
    - name: Upload static files to CDN
      uses: nais/deploy/actions/cdn-upload/v2@master
      with:
        team: ${{ inputs.team }}
        source: .next/static
        destination: '/${{ inputs.app }}/_next'
    - uses: nais/docker-build-push@v0
      name: Build and push image
      id: docker-build-push
      with:
        team: ${{ inputs.team }}
        image_suffix: ${{ inputs.env }}
