import {
    ApiEgenskap,
    ApiOppgaveSorteringsfelt,
    ApiSorteringsrekkefølge,
    GetOppgaverParams,
} from '@io/rest/generated/spesialist.schemas';

export type Oppgaveliste = {
    id: string;
    navn: string;
    params: Omit<GetOppgaverParams, 'sidetall' | 'sidestoerrelse'>;
};

const serialiserListe = (verdier: string[]): string => verdier.join(',');

const enAv = (...grupper: ApiEgenskap[][]): string[] => grupper.map(serialiserListe);
const ingen = (...egenskaper: ApiEgenskap[]): string => serialiserListe(egenskaper);
const varsler = (...varselkoder: string[]): string => serialiserListe(varselkoder);

const ekskluder_varsler_nks = varsler(
    'RV_AY_11',
    'RV_AY_12',
    'RV_AY_3',
    'RV_AY_4',
    'RV_AY_5',
    'RV_AY_6',
    'RV_AY_7',
    'RV_AY_8',
    'RV_AY_9',
    'RV_IT_3',
    'RV_IT_38',
    'RV_IV_1',
    'RV_IV_3',
    'RV_MV_3',
    'RV_OV_3',
    'RV_OV_5',
    'RV_SØ_10',
    'RV_SØ_2',
    'RV_SØ_44',
    'RV_VV_1',
    'RV_VV_4',
    'RV_VV_8',
    'RV_SV_2',
    'RV_SV_5',
    'RV_IT_1',
    'RV_IT_37',
    'RV_IV_11',
);
export const PREDEFINERTE_OPPGAVELISTER: [Oppgaveliste, ...Oppgaveliste[]] = [
    {
        id: 'nks-arbeidsgiver-en-ag',
        navn: 'NKS - Èn arbeidsgiver',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.EN_ARBEIDSGIVER],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'nks-arbeidsgiver-flere-ag',
        navn: 'NKS - Flere arbeidsgivere',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.FLERE_ARBEIDSGIVERE],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'nks-arbeidsgiver-skjonnsfastsettelse',
        navn: 'NKS - Skjønnsfastsettelse',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.SKJONNSFASTSETTELSE],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'nks-brukerutbetaling',
        navn: 'NKS - Brukerutbetaling',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.UTBETALING_TIL_SYKMELDT, ApiEgenskap.DELVIS_REFUSJON, ApiEgenskap.INGEN_UTBETALING],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'restanseteam-arbeidsgiver-skjonnsfastsettelse-flere-ag',
        navn: 'Restanseteam - Skjønnfastsettelse flere arbeidsgivere',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.SKJONNSFASTSETTELSE],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'restanseteam-frilans',
        navn: 'Restanseteam - Frilans',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SOKNAD]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),

            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            tillatteVarsler: varsler('RV_IV_3'),
        },
    },
    {
        id: 'restanseteam-andre-ytelser',
        navn: 'Restanseteam - Andre ytelser',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SOKNAD]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),

            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            tillatteVarsler: varsler(
                'RV_AY_3',
                'RV_AY_4',
                'RV_AY_5',
                'RV_AY_6',
                'RV_AY_7',
                'RV_AY_8',
                'RV_AY_9',
                'RV_AY_11',
                'RV_AY_12',
            ),
        },
    },
    // brukersaker - forlengelser
    {
        id: 'oppgaveliste-1',
        navn: 'Oppgaveliste 1',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-2',
        navn: 'Oppgaveliste 2',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-3',
        navn: 'Oppgaveliste 3',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
                ApiEgenskap.RISK_QA,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-4',
        navn: 'Oppgaveliste 4',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // brukersaker førstegangsbehandling
    {
        id: 'oppgaveliste-5',
        navn: 'Oppgaveliste 5',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
                ApiEgenskap.RISK_QA,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-6',
        navn: 'Oppgaveliste 6',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-7',
        navn: 'Oppgaveliste 7',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-8',
        navn: 'Oppgaveliste 8',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-9',
        navn: 'Oppgaveliste 9',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-10',
        navn: 'Oppgaveliste 10',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // delvis refusjon førstegangsbehandling
    {
        id: 'oppgaveliste-11',
        navn: 'Oppgaveliste 11',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-12',
        navn: 'Oppgaveliste 12',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-13',
        navn: 'Oppgaveliste 13',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-14',
        navn: 'Oppgaveliste 14',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // delvis refusjon forlengelser
    {
        id: 'oppgaveliste-15',
        navn: 'Oppgaveliste 15',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-16',
        navn: 'Oppgaveliste 16',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-17',
        navn: 'Oppgaveliste 17',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // ingen mottaker førstegangs
    {
        id: 'oppgaveliste-18',
        navn: 'Oppgaveliste 18',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-19',
        navn: 'Oppgaveliste 19',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-20',
        navn: 'Oppgaveliste 20',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-21',
        navn: 'Oppgaveliste 21',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // ingen mottaker forlengelse
    {
        id: 'oppgaveliste-22',
        navn: 'Oppgaveliste 22',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-23',
        navn: 'Oppgaveliste 23',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppgaveliste-24',
        navn: 'Oppgaveliste 24',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // risk og skjønn
    {
        id: 'oppgaveliste-25',
        navn: 'Oppgaveliste 25',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA], [ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
];
