import {
    ApiEgenskap,
    ApiOppgaveSorteringsfelt,
    ApiSorteringsrekkefølge,
    GetOppgaverParams,
} from '@io/rest/generated/spesialist.schemas';

export type Oppgaveliste = {
    id: string;
    navn: string;
    params: Omit<GetOppgaverParams, 'sidetall' | 'sidestoerrelse'>;
};

const serialiserListe = (verdier: string[]): string => verdier.join(',');

const enAv = (...grupper: ApiEgenskap[][]): string[] => grupper.map(serialiserListe);
const ingen = (...egenskaper: ApiEgenskap[]): string => serialiserListe(egenskaper);
const varsler = (...varselkoder: string[]): string => serialiserListe(varselkoder);

const ekskluder_varsler_nks = varsler(
    'RV_AY_11',
    'RV_AY_12',
    'RV_AY_3',
    'RV_AY_4',
    'RV_AY_5',
    'RV_AY_6',
    'RV_AY_7',
    'RV_AY_8',
    'RV_AY_9',
    'RV_IT_3',
    'RV_IT_38',
    'RV_IV_1',
    'RV_IV_3',
    'RV_MV_3',
    'RV_OV_3',
    'RV_OV_5',
    'RV_SØ_10',
    'RV_SØ_2',
    'RV_SØ_44',
    'RV_VV_1',
    'RV_VV_4',
    'RV_VV_8',
    'RV_SV_2',
    'RV_SV_5',
    'RV_IT_1',
    'RV_IT_37',
    'RV_IV_11',
);
export const PREDEFINERTE_OPPGAVELISTER: [Oppgaveliste, ...Oppgaveliste[]] = [
    {
        id: 'nks-arbeidsgiver',
        navn: 'NKS',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'nks-arbeidsgiver-skjonnsfastsettelse',
        navn: 'NKS - Skjønnsfastsettelse',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.SKJONNSFASTSETTELSE],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'nks-brukerutbetaling',
        navn: 'NKS - Brukerutbetaling',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv(
                [ApiEgenskap.SOKNAD],
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE],
                [ApiEgenskap.UTBETALING_TIL_SYKMELDT, ApiEgenskap.DELVIS_REFUSJON, ApiEgenskap.INGEN_UTBETALING],
            ),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: ekskluder_varsler_nks,
        },
    },
    {
        id: 'oppdrag-karmøy-5',
        navn: 'Karmøy oppdrag 5',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.UTLAND,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-karmøy-6',
        navn: 'Karmøy oppdrag 6',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.UTLAND,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.EN_ARBEIDSGIVER,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-karmøy-7',
        navn: 'Karmøy oppdrag 7',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.UTLAND,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // brukersaker - forlengelser
    {
        id: 'oppdrag-1',
        navn: 'Oppdrag 1',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-2',
        navn: 'Oppdrag 2',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-3',
        navn: 'Oppdrag 3',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
                ApiEgenskap.RISK_QA,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-4',
        navn: 'Oppdrag 4',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // brukersaker førstegangsbehandling
    {
        id: 'oppdrag-5',
        navn: 'Oppdrag 5',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
                ApiEgenskap.RISK_QA,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-6',
        navn: 'Oppdrag 6',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-7',
        navn: 'Oppdrag 7',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-8',
        navn: 'Oppdrag 8',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-9',
        navn: 'Oppdrag 9',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-10',
        navn: 'Oppdrag 10',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // delvis refusjon førstegangsbehandling
    {
        id: 'oppdrag-11',
        navn: 'Oppdrag 11',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-12',
        navn: 'Oppdrag 12',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-13',
        navn: 'Oppdrag 13',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-14',
        navn: 'Oppdrag 14',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // delvis refusjon forlengelser
    {
        id: 'oppdrag-15',
        navn: 'Oppdrag 15',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-16',
        navn: 'Oppdrag 16',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-17',
        navn: 'Oppdrag 17',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // ingen mottaker førstegangs
    {
        id: 'oppdrag-18',
        navn: 'Oppdrag 18',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-19',
        navn: 'Oppdrag 19',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-20',
        navn: 'Oppdrag 20',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-21',
        navn: 'Oppdrag 21',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.EN_ARBEIDSGIVER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // ingen mottaker forlengelse
    {
        id: 'oppdrag-22',
        navn: 'Oppdrag 22',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-23',
        navn: 'Oppdrag 23',
        params: {
            erTildelt: false,
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORSTEGANGSBEHANDLING,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    {
        id: 'oppdrag-24',
        navn: 'Oppdrag 24',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
    // risk og skjønn
    {
        id: 'oppdrag-25',
        navn: 'Oppdrag 25',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: enAv([ApiEgenskap.RISK_QA], [ApiEgenskap.SKJONNSFASTSETTELSE]),
            ingenAvEgenskapene: ingen(
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.FORLENGELSE,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.UTBETALING_TIL_ARBEIDSGIVER,
                ApiEgenskap.UTLAND,
            ),
            sorteringsfelt: ApiOppgaveSorteringsfelt.opprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
        },
    },
];
