version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆ "
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 7
      exclude:
        - "navikt/sykepenger-github-workflows*"

  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 7
    registries: '*'
    ignore:
      - dependency-name: '@type/node'
      - dependency-name: 'eslint'
        version: ['9.x']
