apiVersion: nais.io/v1
kind: Alert
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  receivers:
    slack:
      channel: "#team-bømlo-alerts"
  alerts:
    - alert: {{app}} har ingen aktive pods
      expr: up{app=~"{{app}}",job="kubernetes-pods"} == 0
      for: 2m
      description: {{app}} mangler aktive pods i preprod!
      action: Se `kubectl describe pod \{{ $labels.kubernetes_pod_name }}` for events,
        og `kubectl logs \{{ $labels.kubernetes_pod_name }}` for logger
      sla: respond within 1h, during office hours
      severity: danger
