apiVersion: "nais.io/v1alpha1"
kind: Alert
metadata:
  name: "speil-alerts"
  labels:
    team: tbd
spec:
  receivers:
    slack:
      channel: "#team-bømlo-alerts"
  alerts:
    - alert: "speil har ingen aktive pods"
      expr: 'up{app=~"speil",job="kubernetes-pods"} == 0'
      for: 2m
      description: "speil mangler aktive pods i preprod!"
      action: "Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
      sla: "respond within 1h, during office hours"
      severity: danger
