apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{team}}
  labels:
    team: {{team}}
spec:
  accessPolicy:
    outbound:
      rules:
        - application: spesialist
          cluster: dev-gcp
          namespace: tbd
        - application: flexjar-backend
          cluster: dev-gcp
          namespace: flex
        - application: modiacontextholder
          namespace: personoversikt
          cluster: dev-gcp
  image: {{image}}
  port: 3000
  ingresses:
    - https://speil.intern.dev.nav.no
    - https://speil.ansatt.dev.nav.no
  liveness:
    failureThreshold: 10
    initialDelay: 10
    path: /api/internal/isAlive
    periodSeconds: 5
    timeout: 1
  readiness:
    initialDelay: 10
    path: /api/internal/isReady
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 2
    min: 2
  resources:
    limits:
      cpu: '2000m'
      memory: '512Mi'
    requests:
      cpu: '50m'
      memory: '128Mi'
  prometheus:
    enabled: true
    path: /api/internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /_next/*
        - /public/*
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: 'cda797bb-ac3b-4440-b661-2cd5eb3edba0' # 0000-CA-Speil-Saksbehandler
          - id: '216b7219-3906-43c5-8e22-03fb74133b42' # 0000-CA-Speil_Lesetilgang
  envFrom:
    - secret: speil
  env:
    - name: LOG_LEVEL
      value: debug
    - name: CLIENT_ID_SPESIALIST
      value: api://dev-gcp.tbd.spesialist/.default
    - name: SPESIALIST_BASE_URL
      value: http://spesialist
    - name: SPARKEL_AAREG_SCOPE
      value: api://dev-gcp.tbd.sparkel-aareg/.default
    - name: SPARKEL_AAREG_BASEURL
      value: http://sparkel-aareg
    - name: FLEXJAR_BASE_URL
      value: http://flexjar-backend.flex
    - name: CLIENT_ID_FLEXJAR
      value: api://dev-gcp.flex.flexjar-backend/.default
    - name: MODIA_BASE_URL
      value: http://modiacontextholder.personoversikt
    - name: MODIA_API_SCOPE
      value: api://dev-gcp.personoversikt.modiacontextholder/.default
    - name: SPESIALIST_WS_URL
      value: ws://spesialist
