module.exports = {
    preset: 'ts-jest',
    moduleFileExtensions: ['js', 'jsx', 'json', 'tsx', 'ts'],
    transform: {
        '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$': 'babel-jest',
        '^.+\\.js$': 'babel-jest',
        '^.+\\.jsx$': 'babel-jest',
        '^.+\\.tsx$': 'ts-jest',
        '^.+\\.ts$': 'ts-jest',
    },
    testEnvironment: 'jsdom',
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/$1',
        '\\.(css|less|sass|scss)$': '<rootDir>/__mocks__/styleMock.js',
        '\\.(gif|ttf|eot|svg|png|graphql\\?raw)$': '<rootDir>/__mocks__/fileMock.js',
        'nav-(.*)-style': '<rootDir>/__mocks__/fileMock.js',
        '@test-data/(.*)$': '<rootDir>/test/data/$1',
        '@test-wrappers': '<rootDir>/test/wrappers',
        '@io/(.*)$': '<rootDir>/io/$1',
        '@components/(.*)$': '<rootDir>/components/$1',
        '@utils/(.*)$': '<rootDir>/utils/$1',
        '@state/(.*)$': '<rootDir>/state/$1',
        '@hooks/(.*)$': '<rootDir>/hooks/$1',
        '@navikt/ds-icons(.*)': '@navikt/ds-icons/cjs$1',
        '@navikt/ds-react-internal(.*)': '@navikt/ds-react-internal/cjs$1',
        '@navikt/ds-react(.*)': '@navikt/ds-react/cjs$1',
        '@navikt/ds-css(.*)': '<rootDir>/__mocks__/styleMock.js',
    },
    transformIgnorePatterns: ['<rootDir>/node_modules'],
    watchPathIgnorePatterns: ['<rootDir>/node_modules'],
    setupFilesAfterEnv: ['<rootDir>/__mocks__/jest-setup.js'],
};
process.env.TZ = 'UTC';
