import dayjs from 'dayjs';

import {
    ApiEgenskap,
    ApiOppgaveSorteringsfelt,
    ApiSorteringsrekkefølge,
    GetOppgaverParams,
} from '@io/rest/generated/spesialist.schemas';

export type Oppgaveliste = {
    id: string;
    navn: string;
    params: Omit<GetOppgaverParams, 'sidetall' | 'sidestoerrelse'>;
};

export const PREDEFINERTE_OPPGAVELISTER: [Oppgaveliste, ...Oppgaveliste[]] = [
    {
        id: 'nks-arbeidsgiver',
        navn: 'NKS',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: [
                [ApiEgenskap.SOKNAD].join(','),
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE].join(','),
            ],
            ingenAvEgenskapene: [
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ].join(','),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: [
                'RV_MV_3',
                'RV_IM_4',
                'RV_VV_1',
                'RV_VV_4',
                'RV_VV_8',
                'RV_IV_1',
                'RV_IV_3',
                'RV_OV_3',
                'RV_OV_5',
                'RV_AY_3',
                'RV_AY_4',
                'RV_AY_5',
                'RV_AY_6',
                'RV_AY_7',
                'RV_AY_8',
                'RV_AY_9',
                'RV_AY_11',
                'RV_AY_12',
                'RV_SØ_2',
                'RV_SØ_10',
                'RV_SØ_44',
                'RV_IT_3',
                'RV_IT_38',
            ].join(','),
        },
    },
    {
        id: 'nks-arbeidsgiver-skjonnsfastsettelse',
        navn: 'NKS - Skjønnsfastsettelse',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: [
                [ApiEgenskap.SOKNAD].join(','),
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE].join(','),
                [ApiEgenskap.SKJONNSFASTSETTELSE].join(','),
            ],
            ingenAvEgenskapene: [
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.UTBETALING_TIL_SYKMELDT,
                ApiEgenskap.DELVIS_REFUSJON,
                ApiEgenskap.INGEN_UTBETALING,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.FLERE_ARBEIDSGIVERE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ].join(','),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: [
                'RV_MV_3',
                'RV_IM_4',
                'RV_VV_1',
                'RV_VV_4',
                'RV_VV_8',
                'RV_IV_1',
                'RV_IV_3',
                'RV_OV_3',
                'RV_OV_5',
                'RV_AY_3',
                'RV_AY_4',
                'RV_AY_5',
                'RV_AY_6',
                'RV_AY_7',
                'RV_AY_8',
                'RV_AY_9',
                'RV_AY_11',
                'RV_AY_12',
                'RV_SØ_2',
                'RV_SØ_10',
                'RV_SØ_44',
                'RV_IT_3',
                'RV_IT_38',
            ].join(','),
        },
    },
    {
        id: 'nks-brukerutbetaling',
        navn: 'NKS - Brukerutbetaling',
        params: {
            erTildelt: false,
            minstEnAvEgenskapene: [
                [ApiEgenskap.SOKNAD].join(','),
                [ApiEgenskap.FORSTEGANGSBEHANDLING, ApiEgenskap.FORLENGELSE].join(','),
                [ApiEgenskap.UTBETALING_TIL_SYKMELDT, ApiEgenskap.DELVIS_REFUSJON, ApiEgenskap.INGEN_UTBETALING],
            ],
            ingenAvEgenskapene: [
                ApiEgenskap.PA_VENT,
                ApiEgenskap.BESLUTTER,
                ApiEgenskap.RETUR,
                ApiEgenskap.HASTER,
                ApiEgenskap.VERGEMAL,
                ApiEgenskap.UTLAND,
                ApiEgenskap.EGEN_ANSATT,
                ApiEgenskap.STIKKPROVE,
                ApiEgenskap.RISK_QA,
                ApiEgenskap.FORTROLIG_ADRESSE,
                ApiEgenskap.TILBAKEDATERT,
                ApiEgenskap.MANGLER_IM,
                ApiEgenskap.MEDLEMSKAP,
                ApiEgenskap.SKJONNSFASTSETTELSE,
                ApiEgenskap.GRUNNBELOPSREGULERING,
                ApiEgenskap.REVURDERING,
            ].join(','),
            sorteringsfelt: ApiOppgaveSorteringsfelt.behandlingOpprettetTidspunkt,
            sorteringsrekkefoelge: ApiSorteringsrekkefølge.STIGENDE,
            ekskluderVarsler: [
                'RV_MV_3',
                'RV_IM_4',
                'RV_VV_1',
                'RV_VV_4',
                'RV_VV_8',
                'RV_IV_1',
                'RV_IV_3',
                'RV_OV_3',
                'RV_OV_5',
                'RV_AY_3',
                'RV_AY_4',
                'RV_AY_5',
                'RV_AY_6',
                'RV_AY_7',
                'RV_AY_8',
                'RV_AY_9',
                'RV_AY_11',
                'RV_AY_12',
                'RV_SØ_2',
                'RV_SØ_10',
                'RV_SØ_44',
                'RV_IT_3',
                'RV_IT_38',
            ].join(','),
            behandlingOpprettetFom: dayjs('2026-05-01'),
            behandlingOpprettetTom: dayjs('2026-05-21'),
        },
    },
];
