name: Setup npm deps
description: Install npm dependencies

inputs:
  NPM_AUTH_TOKEN:
    required: true
    description: Github reader token

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: pnpm
    - shell: bash
      run: echo "NPM_AUTH_TOKEN=${{ inputs.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV
    - shell: bash
      run: pnpm install --frozen-lockfile
