name: Setup npm deps
description: Install npm dependencies

inputs:
  NPM_AUTH_TOKEN:
    required: true
    description: Github reader token

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - shell: bash
      run: npm ci --ignore-scripts
      env:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
