name: Setup npm deps
description: Install npm dependencies

inputs:
  AUTH_TOKEN:
    required: true
    description: Token to authenticate against the npm registry

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: "https://npm.pkg.github.com"
        cache: 'pnpm'
        scope: "@navikt"
    - shell: bash
      run:        
        pnpm install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{ inputs.AUTH_TOKEN }}
