name: Setup npm deps
description: Install npm dependencies

inputs:
  NPM_AUTH_TOKEN:
    required: true
    description: Github reader token

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.json'
    - shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
      env:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
